# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  # increment_version_number
  # commit_version_bump
  # push_to_git_remote
  # # Building and signing
  # match
  # gym
  end
end

platform :android do
  desc "Uploads build to Browserstack's app automate and app live and runs all the tests on uploaded app."
  lane :upload_test do
    # Uploads app to BrowserStack app automate.
    upload_to_browserstack_app_automate(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: "react-native-stock-price-app/android/app/build/outputs/apk/app-debug.apk"
    )

    # Uploads app to BrowserStack app live.
    upload_to_browserstack_app_live(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: "react-native-stock-price-app/android/app/build/outputs/apk/app-debug.apk"
    )
    gradle(task: "test")
  end
end


