# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Description of what the lane does"

  lane :beta do
    match(type: "adhoc", readonly: is_ci, force_for_new_devices: true,
    app_identifier: "com.app.laymui.stockprice")
    build_app(scheme: "reactnativestockprice")
  end

  lane :custom_lane do
    # scan
  
    match(type: "adhoc", readonly: is_ci, force_for_new_devices: true,
      app_identifier: "com.app.laymui.stockprice")
    gym
    # crashlytics
    # add actions here: https://docs.fastlane.tools/actions
    # to generate ipa if you're not uploading to App Store or TestFlight:
    # cd ios && fastlane gym init 
  end
end


platform :android do
  desc "Uploads build to Browserstack's app automate and app live and runs all the tests on uploaded app."
  lane :upload_test do
    # Uploads app to BrowserStack app automate.
    upload_to_browserstack_app_automate(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: "react-native-stock-price-app/android/app/build/outputs/apk/app-debug.apk"
    )

    # Uploads app to BrowserStack app live.
    upload_to_browserstack_app_live(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: "react-native-stock-price-app/android/app/build/outputs/apk/app-debug.apk"
    )
    gradle(task: "test")
  end
end